//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_KitProductDetail
    {
        public decimal KID { get; set; }
        public decimal KPId { get; set; }
        public decimal KitId { get; set; }
        public decimal ProdId { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> RecTimeStatus { get; set; }
        public string LastModified { get; set; }
        public decimal UserId { get; set; }
        public int Qty { get; set; }
        public string Barcode { get; set; }
        public string Itemcode { get; set; }
        public decimal DP { get; set; }
        public decimal Rate { get; set; }
        public decimal BV { get; set; }
    }
}
