//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRefBussiness
    {
        public int ID { get; set; }
        public Nullable<int> IdNo { get; set; }
        public Nullable<decimal> Cv { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> RefIdNo { get; set; }
    }
}
