//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnChallanBill
    {
        public decimal BillId { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string UserBillNo { get; set; }
        public string AgainstBillNo { get; set; }
    }
}
